name: Dependabot Auto Merge

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test
        
      - name: Auto-merge minor and patch updates
        if: contains(github.event.pull_request.title, 'chore(deps)')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Solo auto-merge si son actualizaciones menores o patches
          if [[ "${{ github.event.pull_request.title }}" =~ (patch|minor) ]]; then
            gh pr review --approve "${{ github.event.pull_request.number }}"
            gh pr merge --auto --squash "${{ github.event.pull_request.number }}"
          fi
